alias: Pool Light On
description: Turns on the pool light at sunset
triggers:
  - trigger: sun
    event: sunset
    offset: 0
conditions: []
actions:
  - type: turn_on
    device_id: 16f000549e737a71773c7a3642c892f1
    entity_id: 21f1e5efc7dfa13f2c9e7dec82dd507d
    domain: light
mode: single
